version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    container_name: frontend-react
  api:
    build: ./api
    ports:
      - 5050:5050
    container_name: image-gallery-api