version: '3.8'
services:
  frontend:
    restart: always
    build: ./frontend
    ports:
      - '3000:3000'
    container_name: frontend-react
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    restart: always
    build: ./api
    ports:
      - '5050:5050'
    container_name: image-gallery-api
    volumes:
      - ./api:/app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Secret12
    volumes:
      - mongodb_data:/data/db  

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Secret12
      ME_CONFIG_MONGODB_URL: mongodb://root:Secret12@mongo:27017/
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  mongodb_data:      
    name: mongodb_data